# Configuration script to Travis-CI
arch:
     - amd64
     - ppc64le
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"  
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py > get-poetry.py
  - python get-poetry.py -y --version 1.0.0b3
  - source ~/.poetry/env  
install:
  - pip install pipenv coveralls[yaml]
  - pipenv sync --dev
script:
  - pipenv run pytest --cov src/ofxstatement
  - pipenv run black --check setup.py src
  - pipenv run mypy src
after_success:
  coveralls
jobs: 
  exclude:
    - arch: ppc64le
      python: 3.6
    - arch: ppc64le
      python: 3.7
   
